config/routes.rb
Rails.application.routes.draw do
  resources :pages, except: [:show]
  get "/pages/:permalink" => "pages#permalink", as: :permalink
  # get 'people/index'
  # get 'people/show'
  # get 'films/index'
  # get 'films/show'
  # get 'planets/index'
  # get 'planets/show'
  # get 'species/index'
  # get 'species/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :home, only: %i[index] do
    collection do
      get "search"
    end
  end
  # get "people", to: "people#index"
  # get "people/:id", to: "people#show", id: /\d+/, as: "person"
  resources :people, only: %i[index show]

  get "species", to: "species#index"
  get "species/:id", to: "species#show", id: /\d+/, as: "specie"

  get "planets", to: "planets#index"
  get "planets/:id", to: "planets#show", id: /\d+/, as: "planet"

  get "films", to: "films#index"
  get "films/:id", to: "films#show", id: /\d+/, as: "film"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
  has_many :person_films
  has_many :people, through: :person_films

  has_many :film_planets
  has_many :planets, through: :film_planets

  validates :title, uniqueness: true
  validates :title, presence: true
end

app/models/film_planet.rb
class FilmPlanet < ApplicationRecord
  belongs_to :planet
  belongs_to :film
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
end

app/models/people_film.rb
class PeopleFilm < ApplicationRecord
  belongs_to :person
  belongs_to :film
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :species
  belongs_to :planet
  has_many :person_films
  has_many :films, through: :person_films

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/person_film.rb
class PersonFilm < ApplicationRecord
  belongs_to :person
  belongs_to :film
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_many :people
  has_many :species, through: :people

  has_many :film_planets
  has_many :films, through: :film_planets

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/species.rb
class Species < ApplicationRecord
  has_many :people
  has_many :planets, through: :people
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    @films = Film.order(:title)
  end

  def show
    @film = Film.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @films = Film.order("title")
    @people = Person.order("name")
    @planets = Planet.order("name")
    @species = Species.order("name")
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @people = Person.where("name LIKE ?", wildcard_search)
    @films = Film.where("title LIKE ?", wildcard_search)
    @planets = Planet.where("name LIKE ?", wildcard_search)
    @species = Species.where("name LIKE ?", wildcard_search)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "123", except: %i[index show]
  before_action :set_page, only: %i[show edit update destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def permalink
    @page = Page.find_by(permalink: params[:permalink])
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit; end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to pages_path, notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to pages_path, notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.order(:name)
  end

  def show
    @person = Person.find(params[:id])
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.order(:name)
  end

  def show
    @planet = Planet.find(params[:id])
  end
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  def index
    @species = Species.order(:name)
  end

  def show
    @specie = Species.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/views/home/index.html.erb
<div class="columns">
  <div class="column">
    <h2 class="title is-2">Films</h2>
        <ul>
      <% @films.each do |film|%>
        <li>
            <%= link_to film.title, film_path(film)%>
        </li>
        <% end %>

    </ul>
  </div>

  <div class="column">
    <h2 class="title is-2">People</h2>
    <ul>
      <% @people.each do |person|%>
        <li>
            <%= link_to person.name, person_path(person)%>
        </li>
        <% end %>

    </ul>
  </div>

  <div class="column">
    <h2 class="title is-2">Planets</h2>
     <ul>
      <% @planets.each do |planet|%>
        <li>
            <%= link_to planet.name, planet_path(planet)%>
        </li>
        <% end %>

    </ul>
  </div>

  <div class="column">
    <h2 class="title is-2">Species</h2>
       <ul>
      <% @species.each do |specie|%>
        <li>
            <%= link_to specie.name, specie_path(specie)%>
        </li>
        <% end %>

    </ul>
  </div>

</div>

app/views/home/search.html.erb
<p class="mb-5"> found <%= pluralize(@people.count, 'people')%> when searching for: <%= params[:keywords]%></p>
<ul>
  <% @people.each do |person|%>
    <li>
      <%= link_to person.name, person%>

    </li>
  <% end %>
</ul>
<p class="mb-5"> found <%= pluralize(@species.count, 'species')%> when searching for: <%= params[:keywords]%></p>
<ul>
  <% @species.each do |specie|%>
    <li>
      <%= link_to specie.name, specie_path(specie)%>

    </li>
  <% end %>


</ul>
<p class="mb-5"> found <%= pluralize(@planets.count, 'planets')%> when searching for: <%= params[:keywords]%></p>
<ul>
  <% @planets.each do |planet|%>
    <li>
      <%= link_to planet.name, planet_path(planet)%>

    </li>
  <% end %>


</ul>
<p class="mb-5"> found <%= pluralize(@films.count, 'films')%> when searching for: <%= params[:keywords]%></p>
<ul>
  <% @films.each do |film|%>
    <li>
      <%= link_to film.title, film_path(film)%>

    </li>
  <% end %>


</ul>

app/views/species/index.html.erb
<% if @species.empty?%>
  <p>There are no species available</p>
<% else %>
  <h2 class="title is-2">There are <%= @species.count%> species in the star war films</h2>

  <% @species.each do |specie| %>
    <ul>
      <li>
        <%= link_to specie.name, specie_path(specie) %>
      </li>
    </ul>


  <% end %>
<% end %>

app/views/species/show.html.erb
<h2 class="title is-2"> Species Name: <%= @specie.name %> belongs category <%= link_to "Species", species_path%></h2>
<h3>Species Details:</h3>
<p>
  <strong>The language of this specie is</strong> <%= @specie.language%> <br>
  <strong>The classification of this specie is</strong>  <%= @specie.classification%> <br>


</p>
<h3 class="title is-3">There are <%= @specie.people.count %> people from this specie</h3>
  <ul>
    <% @specie.people.each do |person| %>
      <li>
        <%= link_to person.name, person%>
      </li>
    <% end %>
  </ul>
<h3 class="title is-3">There are <%= @specie.planets.count %> planets have this specie</h3>

 <ul>
    <% @specie.planets.each do |planet| %>
      <li>
         <%= link_to planet.name, planet %>
      </li>
    <% end %>
  </ul>
<p>



</p>