config/routes.rb
Rails.application.routes.draw do
  resources :pages, except: [:show]
  get "/pages/:permalink" => "pages#permalink", as: :permalink
  # get 'people/index'
  # get 'people/show'
  # get 'films/index'
  # get 'films/show'
  # get 'planets/index'
  # get 'planets/show'
  # get 'species/index'
  # get 'species/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :home, only: %i[index] do
    collection do
      get "search"
    end
  end
  # get "people", to: "people#index"
  # get "people/:id", to: "people#show", id: /\d+/, as: "person"
  resources :people, only: %i[index show]

  get "species", to: "species#index"
  get "species/:id", to: "species#show", id: /\d+/, as: "specie"

  get "planets", to: "planets#index"
  get "planets/:id", to: "planets#show", id: /\d+/, as: "planet"

  get "films", to: "films#index"
  get "films/:id", to: "films#show", id: /\d+/, as: "film"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
  has_many :person_films
  has_many :people, through: :person_films

  has_many :film_planets
  has_many :planets, through: :film_planets

  validates :title, uniqueness: true
  validates :title, presence: true
end

app/models/film_planet.rb
class FilmPlanet < ApplicationRecord
  belongs_to :planet
  belongs_to :film
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
end

app/models/people_film.rb
class PeopleFilm < ApplicationRecord
  belongs_to :person
  belongs_to :film
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :species
  belongs_to :planet
  has_many :person_films
  has_many :films, through: :person_films

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/person_film.rb
class PersonFilm < ApplicationRecord
  belongs_to :person
  belongs_to :film
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_many :people
  has_many :species, through: :people

  has_many :film_planets
  has_many :films, through: :film_planets

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/species.rb
class Species < ApplicationRecord
  has_many :people
  has_many :planets, through: :people
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    @films = Film.order(:title)
  end

  def show
    @film = Film.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @films = Film.order("title")
    @people = Person.order("name")
    @planets = Planet.order("name")
    @species = Species.order("name")
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @people = Person.where("name LIKE ?", wildcard_search)
    @films = Film.where("title LIKE ?", wildcard_search)
    @planets = Planet.where("name LIKE ?", wildcard_search)
    @species = Species.where("name LIKE ?", wildcard_search)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "123", except: %i[index show]
  before_action :set_page, only: %i[show edit update destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def permalink
    @page = Page.find_by(permalink: params[:permalink])
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit; end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to pages_path, notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to pages_path, notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.order(:name)
  end

  def show
    @person = Person.find(params[:id])
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.order(:name)
  end

  def show
    @planet = Planet.find(params[:id])
  end
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  def index
    @species = Species.order(:name)
  end

  def show
    @specie = Species.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/views/films/index.html.erb
<% if @films.empty?%>
  <p>There are no films available</p>
<% else %>
  <h2 class="title is-2">There are <%= @films.count%> films of star war films</h2>

  <% @films.each do |film| %>
  <ul>
   <li>
      <%= link_to film.title, film_path(film) %>
    </li>
  </ul>


  <% end %>
<% end %>

app/views/films/show.html.erb
<h2 class="title is-2"> Filim Name: <%= @film.title %> belongs category <%= link_to "Films", films_path%></h2>
<h3>Film Details:</h3>
<p>
  <strong>The director of this film is</strong>  <%= @film.director%> <br>
  <strong>The release date of this film is</strong> <%= @film.release_date%> <br>


</p>
<h3 class="title is-3">There are <%= @film.people.count %> people in this film </h3>
  <ul>
    <% @film.people.each do |person| %>
      <li>
        <%= link_to person.name, person_path(person) %>
      </li>
    <% end %>
  </ul>
<h3 class="title is-3">There are <%= @film.planets.count %> planest in this film</h3>

 <ul>
    <% @film.planets.each do |planet| %>
      <li>
         <%= link_to planet.name, planet_path(planet) %>
      </li>
    <% end %>
  </ul>
<p>

app/views/people/index.html.erb
<% if @people.empty? %>
  <p>There are no people available</p>
<% else %>
  <h2 class="title is-2">There are <%= @people.count%> people in the star war films</h2>

  <% @people.each do |person| %>
    <ul>
      <li>
        <%=link_to person.name, person %>  from  Planet
        <%=link_to person.planet.name, person.planet%> Specise is
        <%=link_to person.species.name, person.species%>
      </li>
    </ul>

  <% end %>
<% end %>

app/views/people/show.html.erb
<h2 class="title is-2">Person Name: <%= @person.name %> belongs category <%= link_to "People", people_path%></h2>
<p>
  <strong>This person belongs to planet</strong>  <%=link_to @person.planet.name, @person.planet%> <br>
   <strong>Species is</strong>  <%=link_to @person.species.name, @person.species%> <br>
   <strong>Birth year is</strong>  <%= @person.birth_year%> <br>
   <strong>Gender is</strong>  <%= @person.gender%>

</p>

<h3 class="title is-3">Films</h3>
<% if @person.films.empty? %>
  <p><%= @person.name%> has never been a film.</p>
<% else %>
  <p>Here are the films <%= @person.name%> was in:</p>
  <ul>
    <% @person.films.each do |film| %>
      <li>
        <%= link_to film.title, film%>
      </li>
    <% end %>
  </ul>

<% end %>

app/views/planets/index.html.erb
<% if @planets.empty?%>
  <p>There are no planets available</p>
<% else %>
  <h2 class="title is-2">There are <%= @planets.count%> planets in the star war films</h2>

  <% @planets.each do |planet| %>
  <ul>
    <li>
      <%= link_to planet.name, planet %>
    </li>

  </ul>


  <% end %>
<% end %>

app/views/planets/show.html.erb
<% content_for(:html_title){@planet.name}%>
<h2> Planet Name: <%= @planet.name %> belongs category <%= link_to "Planets", planets_path%></h2>
<h3>Plantes Details:</h3>
<p>
  <strong>The gravity is</strong> <%= @planet.gravity%> <br>
  <strong>The population is</strong>  <%= @planet.population%> <br>



</p>
<h3>There are <%= @planet.people.count %> people from this planet</h3>
  <ul>
    <% @planet.people.each do |person| %>
      <li>
        <%= link_to person.name, person%>
      </li>
    <% end %>
  </ul>
<h3>There are <%= @planet.species.count %> species from this planet</h3>

 <ul>
    <% @planet.species.each do |specie| %>
      <li>
         <%= link_to specie.name, specie %>
      </li>
    <% end %>
  </ul>
<p>



</p>

<h3>Films</h3>
<% if @planet.films.empty? %>
  <p><%= @planet.name%> has never been a film.</p>
<% else %>
  <p>Here are the films <%= @planet.name%> appeard:</p>
  <ul>
    <% @planet.films.each do |film| %>
      <li>
        <%= link_to film.title, film%>
      </li>
    <% end %>
  </ul>

<% end %>