config/routes.rb
Rails.application.routes.draw do
  resources :pages, except: [:show]
  get "/pages/:permalink" => "pages#permalink", as: :permalink
  # get 'people/index'
  # get 'people/show'
  # get 'films/index'
  # get 'films/show'
  # get 'planets/index'
  # get 'planets/show'
  # get 'species/index'
  # get 'species/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :home, only: %i[index] do
    collection do
      get "search"
    end
  end
  # get "people", to: "people#index"
  # get "people/:id", to: "people#show", id: /\d+/, as: "person"
  resources :people, only: %i[index show]

  get "species", to: "species#index"
  get "species/:id", to: "species#show", id: /\d+/, as: "specie"

  get "planets", to: "planets#index"
  get "planets/:id", to: "planets#show", id: /\d+/, as: "planet"

  get "films", to: "films#index"
  get "films/:id", to: "films#show", id: /\d+/, as: "film"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
  has_many :person_films
  has_many :people, through: :person_films

  has_many :film_planets
  has_many :planets, through: :film_planets

  validates :title, uniqueness: true
  validates :title, presence: true
end

app/models/film_planet.rb
class FilmPlanet < ApplicationRecord
  belongs_to :planet
  belongs_to :film
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
end

app/models/people_film.rb
class PeopleFilm < ApplicationRecord
  belongs_to :person
  belongs_to :film
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :species
  belongs_to :planet
  has_many :person_films
  has_many :films, through: :person_films

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/person_film.rb
class PersonFilm < ApplicationRecord
  belongs_to :person
  belongs_to :film
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_many :people
  has_many :species, through: :people

  has_many :film_planets
  has_many :films, through: :film_planets

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/species.rb
class Species < ApplicationRecord
  has_many :people
  has_many :planets, through: :people
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    @films = Film.order(:title)
  end

  def show
    @film = Film.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @films = Film.order("title")
    @people = Person.order("name")
    @planets = Planet.order("name")
    @species = Species.order("name")
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @people = Person.where("name LIKE ?", wildcard_search)
    @films = Film.where("title LIKE ?", wildcard_search)
    @planets = Planet.where("name LIKE ?", wildcard_search)
    @species = Species.where("name LIKE ?", wildcard_search)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "123", except: %i[index show]
  before_action :set_page, only: %i[show edit update destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def permalink
    @page = Page.find_by(permalink: params[:permalink])
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit; end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to pages_path, notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to pages_path, notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.order(:name)
  end

  def show
    @person = Person.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= yield(:html_title) if content_for?(:html_title)%>Star Wars</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="section">
    <div class="container">
   <h1 class= "title is-1">Star War Films</h1>

<%= form_with(url: search_home_index_path, method: "get", local: true) do %>
  <div class="field is-grouped mb-5">

    <div class="control is-expended">
        <%= text_field_tag(:keywords, nil, class: "input", placeholder: "Search for keyword") %>
    </div>
    <div>
        <%= submit_tag("Search", class: "button is-primary") %>
    </div>


  </div>

<% end %>
    <p>
        <%= link_to 'Home', root_path %> |
        <%= link_to 'People', people_path%> |
        <%= link_to 'Species', species_path%> |
        <%= link_to 'Planets', planets_path%> |
        <%= link_to 'Films', films_path%> |
        <%= link_to 'About The Data', permalink_path('about_the_data')%> |
        <%= link_to 'Pages', pages_path%>

        <br>
        <br>


    </p>
    <%= yield %>
    </div>
    </section>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: 'label' %>
    <%= form.text_field :title, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :content, class: 'label' %>
    <%= form.text_area :content, class: 'textarea' %>
  </div>

  <div class="field">
    <%= form.label :permalink, class: 'label' %>
    <%= form.text_field :permalink, class: 'input' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'button is-primary' %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h2 class="title is-4">Editing Page</h2>

<%= render 'form', page: @page %>

<p class = "mt-5">
<%= link_to 'Back', pages_path %>
</p>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="title is-4">Pages</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Permalink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= truncate page.content %></td>
        <td><%= page.permalink %></td>
        <td><%= link_to 'Edit', edit_page_path(page), class: 'button is-warning' %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path, class: 'button is-primary' %>

app/views/pages/new.html.erb
<h2 class="title is-4">New Page</h2>

<%= render 'form', page: @page %>
<p class = "mt-5">
<%= link_to 'Back', pages_path %>
</p>

app/views/pages/permalink.html.erb
<p id="notice"><%= notice %></p>
<p>
  <h2 class="title is-4">
    <%= @page.title %>
  </h2>
</p>

<p class="mt-5">
  <%= @page.content %>
</p>